In [ ]:
# (1) 첨부된 code에서 Q-Learning이 어떻게 적용되었는지 정리해보세요!
# (2) 코드에서 gamma 값을 0.5 또는 0.99로 바꾸어 실행해보고, gamma 값을 다르게 설정하면 Q-matrix가 어떻게 변하는지 비교하여 정리해보세요!

(1)
- 초기화: Q-matrix는 0으로 시작되고, 보상(reward)과 전이(transition) 행렬이 주어짐
- 탐색: 에이전트는 주어진 상태에서 유효한 행동을 무작위로 선택하고, 그에 따른 보상과 전이를 계산
- Q-값 업데이트: 각 상태-행동에 대해 Q-값을 업데이트하는데, 즉각적인 보상과 미래 보상을 고려하여 업데이트
- 목표 도달: 목표 상태(상태 3)에 도달하면 해당 에피소드는 종료되고, 새로운 에피소드가 시작됨

(2)
- gamma = 0.99는 미래 보상을 중요하게 생각하여 Q-matrix가 더 크게 변화하고, 장기적인 보상을 고려하는 경로를 더 많이 탐색
- 반면 gamma = 0.5는 즉각적인 보상을 더 중요시하여 Q-matrix가 덜 변화하고, 미래 보상을 덜 반영하며 더 짧은 경로를 선택하는 경향이 있음
- 즉, gamma 값이 높을수록 에이전트는 더 멀리 보는 경향이 있고, 낮을수록 단기적인 보상에 집중

In [3]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.5

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state 
# 1 is state to the right of 0
# 2 is the snake-pit state 
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions 
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state])
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3:
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)


[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.  -1.  -1.]
 [  0.   0.   0.   0.   0.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.  -1.  -1.]
 [  0.   0.   0.   0.  -1.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.  -1.  -1.]
 [  0.   0.   0.   0.  -1.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.  -1.  -1.]
 [  0.  10.   0.   0.  -1.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
goal state reached
[[  0. -10.   0.   4.  -1.]
 [  0.  10.   0.   0. 

In [4]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.99

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state 
# 1 is state to the right of 0
# 2 is the snake-pit state 
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions 
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state])
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3:
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)


[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]
 [ -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]
 [ -1.   0.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]
 [ -1.   0.  